"""
Real PDF zoning report, templated to match Connplex's actual "Zoning Layout"
sheet format 1:1 in structure (spec Sec 41/42/7.3/8.7): single portrait sheet,
floor plan on the left, a fixed-width info column on the right containing —
top to bottom — General Notes, Notes, Legends, the Area & Seat Chart, a
Revisions log, a Drawing Issued log with FOR APPROVAL/FOR GFC checkboxes, a Key
Plan box, the project info block, the DRG NO/TITLE/SCALE/DRAWN BY/CHECKED
BY/DATE title block, and the CONNPLEX SMART THEATRES company block with
address and their real logo artwork.

This structure and every static label/legend/notes string below were taken
directly from a real Connplex reference drawing (Keshav Landmark, Vadodara,
DRG ZL-01-R1) supplied by the user, not invented. The logo is the real brand
mark too — extracted directly from a real, later Connplex production drawing
(1159-The Crossroads, Valsad, DRG "Net Usage Area @ 2nd Floor", 21.07.2026)
via `pdfimages`, not redrawn or approximated (see `assets/connplex_logo.jpg`).
"""
import os
from datetime import datetime

from reportlab.lib.pagesizes import A2, portrait
from reportlab.lib.units import inch, mm
from reportlab.lib.colors import HexColor, black, white, red
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as pdfcanvas
from shapely.geometry import Polygon
from shapely.ops import unary_union

LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", "connplex_logo.jpg")
_logo_reader = None

PAGE_SIZE = portrait(A2)
MARGIN = 14 * mm
SIDEBAR_W = 190 * mm
GAP = 6 * mm

# Same hue family per room type as ROOM_COLORS in
# apps/web/src/components/workspace/EditableCanvas.tsx — pastel here for a
# printed white page, saturated there for a dark canvas background. Keep both
# in sync when either changes (see the note in EditableCanvas.tsx for why).
# Scoped to exactly the room types layout_engine.py's SUPPORT_ZONE_DEFAULTS
# and auditorium placement actually produce — CAFE/STORE were dead entries
# for room types the real pipeline never generates.
ROOM_SHORT_LABEL = {
    # Fallback labels for the floor plan only (the Area & Seat Chart and
    # elsewhere still use the full display_name) — used when a room's own
    # on-page footprint is too narrow to fit its real name even after
    # _fit_room_name shrinks to its floor size and wraps, which otherwise
    # let text visibly bleed into a neighboring room (found via real
    # rendering: "BACK-OF-HOUSE (ELECTRICAL / SERVER / STORE)" overflowing
    # into an adjacent Washroom box). Room types with already-short names
    # (FOYER, WASHROOM) don't need an entry.
    "BOH": "BOH",
    "FNB": "F&B",
    "BOX_OFFICE": "BOX OFFICE",
}

ROOM_FILL = {
    "AUDITORIUM": HexColor("#d9d2f0"),  # violet
    "FOYER": HexColor("#cdefd6"),       # green
    "FNB": HexColor("#f5dcb8"),         # amber
    "WASHROOM": HexColor("#c9e0f5"),    # blue
    "BOX_OFFICE": HexColor("#f5d6e6"),  # magenta
    "BOH": HexColor("#dcdce2"),         # slate
}

COMPANY_NAME = "CONNPLEX SMART THEATRES"
COMPANY_ADDRESS_LINES = [
    "Address: VCS Industries Limited 703, Titanium One, nr. Rajpath Club, SG",
    "Highway, Ahmedabad - 380054 Gujarat",
    "E: drawings@theconnplex.com   Mo: +91 97666 47609",
]
COMPANY_WEBSITE = "Website : www.theconnplex.com"

GENERAL_NOTE = ("THIS DRAWING IS THE PROPERTY OF CONNPLEX SMART THEATRES AND NOT TO BE "
                "COPIED OR USED WITHOUT OUR PERMISSION")
NOTES = [
    "ALL DIMENSIONS ARE TO BE CHECKED AND CO-RELATED WITH THE ARCHITECTURAL/"
    "INTERIOR DRAWINGS AND ANY AMBIGUITY SHALL BE IMMEDIATELY BROUGHT TO THE "
    "NOTICE OF THE ARCHITECT BEFORE COMMENCEMENT OF THE WORK.",
    "ALL DRAWINGS ARE TO BE READ AND NOT TO BE MEASURED.",
    "ALL DIMENSIONS ARE IN FEET-INCH.",
    "THIS DRAWING WAS GENERATED BY SOFTWARE (ZONING ENGINE) AND MAY NOT BE "
    "FULLY ACCURATE — VERIFY ALL DIMENSIONS AND LAYOUT BEFORE CONSTRUCTION "
    "OR SUBMISSION.",
]
LEGEND_ITEMS = [
    ("UFL", "UNFINISHED FLOOR LEVEL"), ("TB", "TRUSS BOTTOM LEVEL"),
    ("FFL", "FINISHED FLOOR LEVEL"), ("LS", "LAST STEP LEVEL"),
    ("SB", "SLAB BOTTOM LEVEL"), ("FC", "FALSE CEILING LEVEL"),
    ("BB", "BEAM BOTTOM LEVEL"), ("GFC", "GOOD FOR CONSTRUCTION"),
]


def _fmt_ft_in(value_ft):
    """Decimal feet -> architectural feet-inch string, matching this sheet's
    own 'ALL DIMENSIONS ARE IN FEET-INCH' note."""
    total_in = round(value_ft * 12)
    ft, inch_part = divmod(total_in, 12)
    return f"{ft}'-{inch_part}\""


def _fit_room_name(c, name, max_w, start_size, floor_size=4.2):
    """Fit a room name within max_w: shrink the font first, then — if it still
    won't fit even at the floor size — wrap onto a second line split at the
    best space. Long real names ('FOOD & BEVERAGE / CONCESSION') in narrow
    rooms otherwise spill past the room's drawn boundary."""
    size = start_size
    while size > floor_size and c.stringWidth(name, "Helvetica-Bold", size) > max_w:
        size -= 0.4
    if c.stringWidth(name, "Helvetica-Bold", size) <= max_w or " " not in name:
        return [name], size

    words = name.split(" ")
    best = None
    for i in range(1, len(words)):
        line1, line2 = " ".join(words[:i]), " ".join(words[i:])
        w = max(c.stringWidth(line1, "Helvetica-Bold", size), c.stringWidth(line2, "Helvetica-Bold", size))
        if best is None or w < best[0]:
            best = (w, line1, line2)
    _, line1, line2 = best
    while size > floor_size and max(c.stringWidth(line1, "Helvetica-Bold", size), c.stringWidth(line2, "Helvetica-Bold", size)) > max_w:
        size -= 0.4
    return [line1, line2], size


def _room_color(room_type):
    key = room_type.split("_")[0] if room_type.startswith("AUDITORIUM") else room_type
    return ROOM_FILL.get(key, HexColor("#eeeeee"))


def _draw_logo(c, x, y, w, h):
    """Real Connplex badge artwork (see LOGO_PATH), drawn at its true aspect
    ratio and centered in the (w, h) box rather than stretched to fill it."""
    global _logo_reader
    if _logo_reader is None:
        _logo_reader = ImageReader(LOGO_PATH)
    img_w, img_h = _logo_reader.getSize()
    scale = min(w / img_w, h / img_h)
    draw_w, draw_h = img_w * scale, img_h * scale
    c.drawImage(_logo_reader, x + (w - draw_w) / 2, y + (h - draw_h) / 2, draw_w, draw_h, mask="auto")


def _box(c, x, y, w, h, label=None, label_size=6.5):
    c.setStrokeColor(black)
    c.setLineWidth(0.6)
    c.rect(x, y, w, h, stroke=1, fill=0)
    if label:
        c.setFont("Helvetica-Bold", label_size)
        c.setFillColor(black)
        c.drawString(x + 3, y + h - label_size - 3, label)


def _wrap_text(c, text, font, size, max_w):
    c.setFont(font, size)
    words = text.split()
    lines, cur = [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if c.stringWidth(trial, font, size) <= max_w:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


LABEL_CLEARANCE = 13  # vertical gap (pt) reserved below a box's top-left label before content starts


def _draw_general_notes(c, x, y_top, w):
    h = 24 * mm
    _box(c, x, y_top - h, w, h, "GENERAL NOTES :-")
    lines = _wrap_text(c, GENERAL_NOTE, "Helvetica", 6, w - 8)
    ty = y_top - LABEL_CLEARANCE - 6
    c.setFont("Helvetica", 6)
    for line in lines:
        c.drawString(x + 4, ty, line)
        ty -= 7.5
    return y_top - h


def _draw_notes(c, x, y_top, w):
    h = 42 * mm  # bumped from 32mm to fit the software-generated-accuracy disclaimer (4th note, wraps to 2 lines)
    _box(c, x, y_top - h, w, h, "NOTES :-")
    ty = y_top - LABEL_CLEARANCE - 6
    c.setFont("Helvetica", 6)
    for i, note in enumerate(NOTES, start=1):
        lines = _wrap_text(c, f"{i}. {note}", "Helvetica", 6, w - 8)
        for line in lines:
            c.drawString(x + 4, ty, line)
            ty -= 7.2
    return y_top - h


def _draw_legends(c, x, y_top, w):
    h = 25 * mm
    _box(c, x, y_top - h, w, h, "LEGENDS :-")
    col_w = w / 2
    top = y_top - LABEL_CLEARANCE - 6
    c.setFont("Helvetica", 5.8)
    for i, (abbr, meaning) in enumerate(LEGEND_ITEMS):
        col = i // 4
        row = i % 4
        cx = x + 4 + col * col_w
        cy = top - row * 8.5
        c.setFillColor(red)
        c.setFont("Helvetica-Bold", 5.8)
        c.drawString(cx, cy, abbr)
        c.setFillColor(black)
        c.setFont("Helvetica", 5.5)
        c.drawString(cx + 22, cy, meaning)
    return y_top - h


def _draw_area_seat_chart(c, x, y_top, w, chart):
    col_w = [w * 0.32, w * 0.13, w * 0.11, w * 0.14, w * 0.12, w * 0.12, w * 0.06]
    headers = ["LOCATION", "AREA", "LNGR", "SOFA\nSLD", "DUO\nLNGR", "PREM\nRECL", "TOT"]
    row_h = 7.4 * mm
    header_h = 16 * mm
    n_data_rows = len(chart["screen_rows"]) + 3
    h = header_h + n_data_rows * row_h + 4 * mm
    _box(c, x, y_top - h, w, h, "AREA CHART(SQ.FT.) & SEAT CHART")

    ty = y_top - LABEL_CLEARANCE - 10
    cx = x
    c.setFont("Helvetica-Bold", 5.4)
    for header, cw in zip(headers, col_w):
        for j, part in enumerate(header.split("\n")):
            c.drawCentredString(cx + cw / 2, ty - j * 5.5, part)
        cx += cw
    c.line(x, ty - 12, x + w, ty - 12)
    y = ty - 20

    def zb(v):  # zero/blank helper — show a real 0 as blank, matching the reference sheet's convention
        return v if v else ""

    def row(cells, bold=False, fill=None):
        nonlocal y
        if fill:
            c.setFillColor(fill)
            c.rect(x, y - 4, w, row_h, stroke=0, fill=1)
        c.setFillColor(black)
        c.setFont("Helvetica-Bold" if bold else "Helvetica", 5.4)
        cxi = x
        for cell, cw in zip(cells, col_w):
            c.drawCentredString(cxi + cw / 2, y, str(cell))
            cxi += cw
        y -= row_h

    for r in chart["screen_rows"]:
        row([r["location"], f"{r['area_sqft']:,.0f}", zb(r["lounger"]), zb(r["sofa_slider"]),
             zb(r["duo_lounger"]), zb(r["premium_recliner"]), r["total_seats"]])

    t = chart["total_screen_row"]
    row(["TOTAL SCREEN", f"{t['area_sqft']:,.0f}", zb(t["lounger"]), zb(t["sofa_slider"]),
         zb(t["duo_lounger"]), zb(t["premium_recliner"]), t["total_seats"]], bold=True, fill=HexColor("#f0f0f0"))

    f_ = chart["foyer_row"]
    row(["FOYER", f"{f_['area_sqft']:,.0f}", "", "", "", "", ""])
    e = chart["exit_passage_row"]
    row([e["location"], f"{e['area_sqft']:,.0f}", "", "", "", "", ""])

    g = chart["grand_total_row"]
    row(["TOTAL", f"{g['area_sqft']:,.0f}", zb(g["lounger"]), zb(g["sofa_slider"]), zb(g["duo_lounger"]),
         zb(g["premium_recliner"]), g["total_seats"]], bold=True, fill=HexColor("#ffd7d7"))

    return y_top - h


def _draw_revisions(c, x, y_top, w):
    h = 34 * mm
    _box(c, x, y_top - h, w, h, "REVISIONS :-")
    col_w = [w * 0.12, w * 0.18, w * 0.55, w * 0.15]
    headers = ["NO.", "DATE", "REMARKS", "R.BY"]
    ty = y_top - LABEL_CLEARANCE - 6
    c.setFont("Helvetica-Bold", 5.6)
    cx = x
    for hd, cw in zip(headers, col_w):
        c.drawCentredString(cx + cw / 2, ty, hd)
        cx += cw
    c.line(x, ty - 3, x + w, ty - 3)
    for i in range(1, len(col_w)):
        lx = x + sum(col_w[:i])
        c.line(lx, y_top - h, lx, ty + 8)
    return y_top - h


def _draw_drawing_issued(c, x, y_top, w, revision):
    h = 26 * mm
    _box(c, x, y_top - h, w, h, "DRAWING ISSUED :-")
    top = y_top - LABEL_CLEARANCE - 6
    c.setFont("Helvetica", 5.6)
    c.drawString(x + 4, top, f"NOS. Email  App. {revision}")
    c.drawString(x + 4, top - 8, f"DATE: {datetime.utcnow().strftime('%d/%m/%Y')}")
    box_size = 7
    by = top - 20
    c.setFillColor(black)
    c.rect(x + 4, by, box_size, box_size, stroke=1, fill=1)
    c.setFont("Helvetica", 5.8)
    c.drawString(x + 4 + box_size + 3, by + 1, "FOR APPROVAL")
    c.setFillColor(white)
    c.rect(x + 90, by, box_size, box_size, stroke=1, fill=1)
    c.setFillColor(black)
    c.drawString(x + 90 + box_size + 3, by + 1, "FOR GFC")
    return y_top - h


def _draw_key_plan(c, x, y_top, w):
    h = 26 * mm
    _box(c, x, y_top - h, w, h, "KEY PLAN :-")
    return y_top - h


def _draw_project_info(c, x, y_top, w, project_meta, region_meta):
    h = 34 * mm
    _box(c, x, y_top - h, w, h)
    fields = [
        ("PROJECT CODE", project_meta.get("project_code", "-")),
        ("PROPERTY NAME", (project_meta.get("property_name") or "-").upper()),
        ("CITY / STATE", f"{project_meta.get('city','-')} / {project_meta.get('state','-')}".upper()),
        ("CLIENT", project_meta.get("client_name", "-")),
        ("CLIENT BY", project_meta.get("client_by", "-")),
        ("NET USAGE AREA", f"{region_meta.get('net_usage_area_sqft','-')} SQ.FT"),
        ("FLOOR / HEIGHT", f"{project_meta.get('floor_shop_no','-')} / {project_meta.get('beam_bottom_clear_height','-')}"),
    ]
    ty = y_top - 10
    for label, value in fields:
        c.setFont("Helvetica", 5.8)
        c.setFillColor(HexColor("#444444"))
        c.drawString(x + 4, ty, f"{label} :")
        c.setFont("Helvetica-Bold", 6.4)
        c.setFillColor(black)
        c.drawString(x + 62, ty, str(value)[:40])
        ty -= 8.5
    return y_top - h


def _draw_title_stamp(c, x, y_top, w, project_meta, sheet_type):
    h = 34 * mm
    _box(c, x, y_top - h, w, h)
    fields = [
        ("DRG NO. :-", project_meta.get("drg_no", f"ZL-01-{project_meta.get('revision', 'R0')}")),
        ("TITLE :-", sheet_type.upper()),
        ("SCALE :", "N.T.S"),
        ("DRAWN BY :", project_meta.get("drawn_by", "AR. ZONING ENGINE")),
        ("CHECKED BY :", project_meta.get("checked_by", "-")),
        ("DATE :", project_meta.get("generated_at", datetime.utcnow().strftime("%d/%m/%Y"))),
    ]
    ty = y_top - 12
    for label, value in fields:
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(black)
        c.drawString(x + 4, ty, label)
        c.setFont("Helvetica", 7)
        c.drawString(x + 70, ty, str(value)[:34])
        ty -= 9.5
    return y_top - h


def _draw_company_block(c, x, y_top, w):
    h = 40 * mm
    _box(c, x, y_top - h, w, h)
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(black)
    c.drawString(x + 4, y_top - 12, COMPANY_NAME)
    c.setFont("Helvetica", 5.6)
    ty = y_top - 21
    for line in COMPANY_ADDRESS_LINES:
        c.drawString(x + 4, ty, line)
        ty -= 7
    c.setFont("Helvetica", 5.6)
    c.drawString(x + 4, ty - 2, COMPANY_WEBSITE)
    _draw_logo(c, x + w - 46 * mm, y_top - h + 4, 42 * mm, 14 * mm)
    return y_top - h


def _draw_floor_plan(c, boundary_points_ft, obstacles, rooms, plan_x, plan_y, plan_w, plan_h, sheet_type="Zoning Layout"):
    if not boundary_points_ft:
        return
    xs = [p[0] for p in boundary_points_ft]
    ys = [p[1] for p in boundary_points_ft]
    bw, bh = max(xs) - min(xs), max(ys) - min(ys)
    if bw <= 0 or bh <= 0:
        return

    # Title/scale header at the top of the box, and dimension lines along the
    # drawing, both take a slice of the box's own available space rather than
    # the full box — real footprints (esp. a single confirmed region) are
    # often much wider than tall relative to a portrait sheet, so the plan
    # alone would otherwise leave a large, unlabelled blank area above/below it.
    header_h = 20 * mm
    dim_h = 12 * mm
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(black)
    c.drawString(plan_x + 4, plan_y + plan_h - 14, f"FLOOR PLAN — {sheet_type.upper()}")
    c.setFont("Helvetica", 7.5)
    c.setFillColor(HexColor("#444444"))
    c.drawString(plan_x + 4, plan_y + plan_h - 24, "SCALE : N.T.S.")

    draw_x, draw_y = plan_x, plan_y + dim_h
    draw_w, draw_h = plan_w, plan_h - header_h - dim_h

    # A confirmed region is often much wider than tall (or vice versa) relative
    # to this portrait sheet's drawing area. Rather than fit it as-is and leave
    # most of the sheet blank, rotate 90° whenever that orientation lets the
    # plan actually use more of the available area — the same call a drafter
    # fitting a plan to a sheet would make. Only geometry is rotated; room/
    # dimension labels are still drawn upright via drawCentredString, so text
    # stays horizontal and readable either way.
    scale_normal = min(draw_w / bw, draw_h / bh)
    scale_rotated = min(draw_w / bh, draw_h / bw)
    rotated = scale_rotated > scale_normal * 1.1
    scale = (scale_rotated if rotated else scale_normal) * 0.94
    min_x, min_y = min(xs), min(ys)

    if rotated:
        ox = draw_x + (draw_w - bh * scale) / 2
        oy = draw_y + (draw_h - bw * scale) / 2

        def tx(pt):
            return (ox + (pt[1] - min_y) * scale, oy + (pt[0] - min_x) * scale)
    else:
        ox = draw_x + (draw_w - bw * scale) / 2 - min_x * scale
        oy = draw_y + (draw_h - bh * scale) / 2 - min_y * scale

        def tx(pt):
            return (ox + pt[0] * scale, oy + pt[1] * scale)

    c.setStrokeColor(black)
    c.setLineWidth(1.6)
    c.setFillColor(white)
    path = c.beginPath()
    px, py = tx(boundary_points_ft[0])
    path.moveTo(px, py)
    for p in boundary_points_ft[1:]:
        x, y = tx(p)
        path.lineTo(x, y)
    path.close()
    c.drawPath(path, stroke=1, fill=1)

    def draw_obstacle_shape(pts):
        c.setFillColor(HexColor("#555555"))
        c.setStrokeColor(black)
        c.setLineWidth(0.5)
        path = c.beginPath()
        x0, y0 = tx(pts[0])
        path.moveTo(x0, y0)
        for p in pts[1:]:
            x, y = tx(p)
            path.lineTo(x, y)
        path.close()
        c.drawPath(path, stroke=1, fill=1)

    for obs in obstacles or []:
        pts = obs.get("points_ft") if isinstance(obs, dict) else obs
        draw_obstacle_shape(pts)

    for room in rooms:
        pts = room["geometry_points_ft"]
        c.setFillColor(_room_color(room["room_type"]))
        c.setStrokeColor(black)
        c.setLineWidth(1.1)
        path = c.beginPath()
        x0, y0 = tx(pts[0])
        path.moveTo(x0, y0)
        for p in pts[1:]:
            x, y = tx(p)
            path.lineTo(x, y)
        path.close()
        c.drawPath(path, stroke=1, fill=1)

        page_pts = [tx(p) for p in pts]
        rw = max(p[0] for p in page_pts) - min(p[0] for p in page_pts)
        rh = max(p[1] for p in page_pts) - min(p[1] for p in page_pts)
        cx = sum(p[0] for p in pts) / len(pts)
        cy = sum(p[1] for p in pts) / len(pts)
        lx, ly = tx((cx, cy))

        seat = room.get("seat_estimate") or {}
        seat_count = seat.get("seat_count")
        name = room["display_name"].upper()
        start_size = max(min(rw, rh) * 0.11, 6)
        # Fit the name to the room's actual on-page width, rather than letting
        # it spill past the room's boundary — real rooms vary a lot in shape.
        name_lines, name_size = _fit_room_name(c, name, rw * 0.92, start_size)
        widest_line = max(c.stringWidth(ln, "Helvetica-Bold", name_size) for ln in name_lines)
        if widest_line > rw * 0.92 and room["room_type"] in ROOM_SHORT_LABEL:
            # Even the shrunk/wrapped full name still doesn't fit this room's
            # real on-page width (small support zone, long display name) —
            # fall back to a short label instead of letting it bleed outside
            # the room's own box (see ROOM_SHORT_LABEL above for why).
            name = ROOM_SHORT_LABEL[room["room_type"]]
            name_lines, name_size = _fit_room_name(c, name, rw * 0.92, start_size)
        extra = len(name_lines) - 1
        c.setFillColor(black)
        c.setFont("Helvetica-Bold", name_size)
        line_y = ly + (name_size * 0.8 if seat_count else 0) + extra * name_size * 0.55
        for i, ln in enumerate(name_lines):
            c.drawCentredString(lx, line_y - i * name_size * 1.1, ln)
        name_bottom_y = line_y - extra * name_size * 1.1
        if seat_count:
            c.setFont("Helvetica-Bold", name_size * 0.95)
            c.drawCentredString(lx, name_bottom_y - name_size * 1.2, str(seat_count))
            breakdown = seat.get("seat_breakdown", {})
            by = name_bottom_y - name_size * 2.3
            c.setFont("Helvetica", name_size * 0.62)
            for label, key in [("SOFA SLIDER", "SOFA_SLIDER"), ("FRONT LOUNGER", "LOUNGER"), ("PREMIUM RECLINER", "PREMIUM_RECLINER")]:
                if breakdown.get(key):
                    c.drawCentredString(lx, by, f"{label} : {breakdown[key]}")
                    by -= name_size * 0.85
        else:
            c.setFont("Helvetica", name_size * 0.7)
            c.drawCentredString(lx, name_bottom_y - name_size * 1.1, f"{room['area_sqft']:,.0f} SQ.FT")

    # A confirmed obstacle (typically a structural column) can legitimately
    # fall inside a room now (layout_engine.py's two-tier placement allows a
    # room to enclose a COLUMN, never any other obstacle type) — redraw any
    # obstacle whose real footprint intersects a placed room's footprint on
    # top of the room's opaque fill drawn above, so it stays visible the way
    # a real architectural drawing shows a column through a room rather than
    # hiding it underneath.
    room_polys_ft = []
    for room in rooms:
        try:
            room_polys_ft.append(Polygon(room["geometry_points_ft"]))
        except Exception:
            continue
    for obs in obstacles or []:
        pts = obs.get("points_ft") if isinstance(obs, dict) else obs
        try:
            obs_poly = Polygon(pts)
        except Exception:
            continue
        if not obs_poly.is_valid or obs_poly.area <= 0:
            continue
        if any(obs_poly.intersects(rp) for rp in room_polys_ft):
            draw_obstacle_shape(pts)

    # "Net Usage Area" sheets are a real, separate deliverable Connplex
    # actually produces (confirmed against multiple real client reference
    # PDFs, e.g. 1159-The Crossroads' "NET USAGE AREA @ 2nd Floor" and
    # 1158/1073's "..._NET USAGE AREA_..." files) — same floor plan and same
    # Area & Seat Chart as a Zoning Layout sheet, but with the real net
    # usable area called out directly on the drawing via a hatched overlay +
    # label, not just buried in the project-info block. This is a best-effort
    # match to that convention, not a traced copy — see this file's module
    # docstring.
    if "net usage area" in sheet_type.lower() and room_polys_ft:
        net_union = unary_union(room_polys_ft)
        net_area_sqft = net_union.area
        c.saveState()
        clip_path = c.beginPath()
        polys = [net_union] if net_union.geom_type == "Polygon" else list(net_union.geoms)
        for poly in polys:
            x0, y0 = tx(list(poly.exterior.coords)[0])
            clip_path.moveTo(x0, y0)
            for p in list(poly.exterior.coords)[1:]:
                x, y = tx(p)
                clip_path.lineTo(x, y)
            clip_path.close()
        c.clipPath(clip_path, stroke=0, fill=0)
        c.setStrokeColor(HexColor("#c0392b"))
        c.setLineWidth(0.5)
        hatch_step = 8
        page_pts_all = [tx(p) for p in boundary_points_ft]
        hx0 = min(p[0] for p in page_pts_all) - draw_h
        hx1 = max(p[0] for p in page_pts_all) + draw_h
        hy0 = min(p[1] for p in page_pts_all)
        hy1 = max(p[1] for p in page_pts_all)
        x = hx0
        while x < hx1:
            c.line(x, hy0, x + (hy1 - hy0), hy1)
            x += hatch_step
        c.restoreState()

        label_x = draw_x + draw_w / 2
        label_y = draw_y + draw_h * 0.5
        label = f"NET USAGE AREA = {net_area_sqft:,.0f} SQ.FT"
        c.setFont("Helvetica-Bold", 13)
        text_w = c.stringWidth(label, "Helvetica-Bold", 13)
        c.setFillColor(white)
        c.rect(label_x - text_w / 2 - 6, label_y - 6, text_w + 12, 18, stroke=0, fill=1)
        c.setStrokeColor(HexColor("#c0392b"))
        c.setLineWidth(1)
        c.rect(label_x - text_w / 2 - 6, label_y - 6, text_w + 12, 18, stroke=1, fill=0)
        c.setFillColor(HexColor("#c0392b"))
        c.drawCentredString(label_x, label_y - 1, label)

    # Overall dimension line under the drawing — real bounding-box size of the
    # confirmed region (in whichever axis now runs horizontal on the page,
    # after any rotation above), not an invented/rounded scale figure.
    page_pts = [tx(p) for p in boundary_points_ft]
    page_min_x = min(p[0] for p in page_pts)
    page_max_x = max(p[0] for p in page_pts)
    horiz_ft = (page_max_x - page_min_x) / scale
    x0, x1 = page_min_x, page_max_x
    dim_y = plan_y + dim_h * 0.45
    c.setStrokeColor(HexColor("#444444"))
    c.setLineWidth(0.5)
    c.line(x0, dim_y, x1, dim_y)
    c.line(x0, dim_y - 3, x0, dim_y + 3)
    c.line(x1, dim_y - 3, x1, dim_y + 3)
    c.setFont("Helvetica", 7.5)
    c.setFillColor(HexColor("#444444"))
    c.drawCentredString((x0 + x1) / 2, dim_y + 4, _fmt_ft_in(horiz_ft))


def render_pdf(project_meta: dict, boundary_points_ft, rooms, chart: dict, feasibility: dict, out_path: str,
                sheet_type="Zoning Layout", obstacles=None, region_meta=None):
    region_meta = region_meta or {}
    page_w, page_h = PAGE_SIZE
    c = pdfcanvas.Canvas(out_path, pagesize=PAGE_SIZE)

    sidebar_x = page_w - MARGIN - SIDEBAR_W
    plan_x, plan_y = MARGIN, MARGIN
    plan_w = sidebar_x - GAP - MARGIN
    plan_h = page_h - 2 * MARGIN

    _draw_floor_plan(c, boundary_points_ft, obstacles, rooms, plan_x, plan_y, plan_w, plan_h, sheet_type)
    c.setStrokeColor(black)
    c.setLineWidth(1)
    c.rect(plan_x, plan_y, plan_w, plan_h, stroke=1, fill=0)

    y = page_h - MARGIN
    y = _draw_general_notes(c, sidebar_x, y, SIDEBAR_W)
    y = _draw_notes(c, sidebar_x, y, SIDEBAR_W)
    y = _draw_legends(c, sidebar_x, y, SIDEBAR_W)
    y = _draw_area_seat_chart(c, sidebar_x, y, SIDEBAR_W, chart)

    revisions_top = plan_y + 210 * mm
    y2 = _draw_revisions(c, sidebar_x, revisions_top, SIDEBAR_W)
    y2 = _draw_drawing_issued(c, sidebar_x, y2, SIDEBAR_W, project_meta.get("revision", "R0"))
    y2 = _draw_key_plan(c, sidebar_x, y2, SIDEBAR_W)
    y2 = _draw_project_info(c, sidebar_x, y2, SIDEBAR_W, project_meta, region_meta)
    y2 = _draw_title_stamp(c, sidebar_x, y2, SIDEBAR_W, project_meta, sheet_type)
    _draw_company_block(c, sidebar_x, y2, SIDEBAR_W)

    c.save()
    return out_path
